### ISSUE TITLE
Pickling error when using extensions on Windows

### ISSUE THREAD

**Issue by dimp-gh** [tarekziade/molotov#101]
## The issue

Molotov 1.4 crashes when launched in multiprocess mode with extensions.

OS: Windows 10
Python version: 3.5.4, 3.6.3

Stacktrace:
```
C:\tau>molotov --processes 2 --use-extension=molotov.tests.example5 blazedemo.py
**** Molotov v1.4. Happy breaking! ****
Loading extension 'molotov.tests.example5'
Traceback (most recent call last):
  File "c:\program files\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\Scripts\molotov.exe\__main__.py", line 9, in <module>
  File "c:\program files\python35\lib\site-packages\molotov\run.py", line 138, in main
    return run(args)
  File "c:\program files\python35\lib\site-packages\molotov\run.py", line 202, in run
    res = Runner(args)()
  File "c:\program files\python35\lib\site-packages\molotov\runner.py", line 52, in __call__
    return self._launch_processes()
  File "c:\program files\python35\lib\site-packages\molotov\runner.py", line 75, in _launch_processes
    p.start()
  File "c:\program files\python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\program files\python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\program files\python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\program files\python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\program files\python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function print_request at 0x000001C6EA7F4488>: it's not the same object as molotov.tests.example5.print_request
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\program files\python35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input
```

## How to reproduce

Run `molotov --processes 2 --use-extension=molotov.tests.example5 molotov.tests.example2` on Windows 10 command prompt with Python 3.5 and molotov 1.4 installed.

Using extensions other that `molotov.tests.example5` reproduces the crash too.

This looks a bit like yet another Python's Windows issue which should be worked around.

**Comment by tarekziade** [comment]
mmm Interesting... I think that's because of the decorator. I'll investigate

**Comment by tarekziade** [comment]
I moved to dill for the pickling, could you try again with  the lasest master?

**Comment by tarekziade** [comment]
closing-- reopen if you get this again
